server:
  port: 8200
  servlet:
    context-path: /springboot-servlet
  
spring:
  application:
     name: springboot-servlet
  datasource:
     name: mysql
     #type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://101.201.67.138:3306/smartwf-sm?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
     username: root
     password: wind2@
     max-idle: 10
     max-wait: 10000
     min-idle: 5
     initial-size: 5
     # 德鲁伊连接池的补充设置，应用到上面所有数据源中
     initialSize: 5
     minIdle: 5
     maxActive: 20
     # 配置获取连接等待超时的时间
     maxWait: 60000
     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
     timeBetweenEvictionRunsMillis: 60000
     # 配置一个连接在池中最小生存的时间，单位是毫秒
     minEvictableIdleTimeMillis: 300000
     validationQuery: SELECT 1 FROM DUAL
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
     filters: stat,wall,log4j
     logSlowSql: true
        
# 打开feign 的服务降级
feign:
  circuitbreaker:
    enabled: true # 开启服务降级  
  client:
      config:
        default:
          connectTimeout: 5000        #默认连接超时时间
          readTimeout: 5000           #默认读取超时时间
          loggerLevel: basic          #默认日志级别  
          
